return {
  ["builtin"] =             { tag = "var", contents = "_compiler.builtin",                  },
  ["builtin?"] =            { tag = "var", contents = "_compiler[\"builtin?\"]",            },
  ["constant?"] =           { tag = "var", contents = "_compiler[\"constant?\"]",           },
  ["node->val"] =           { tag = "var", contents = "_compiler[\"node->val\"]",           },
  ["node-contains-var?"] =  { tag = "var", contents = "_compiler[\"node-contains-var?\"]",  },
  ["node-contains-vars?"] = { tag = "var", contents = "_compiler[\"node-contains-vars?\"]", },
  ["symbol->var"] =         { tag = "var", contents = "_compiler[\"symbol->var\"]",         },
  ["traverse-node"] =       { tag = "var", contents = "_compiler[\"traverse-node\"]",       },
  ["traverse-nodes"] =      { tag = "var", contents = "_compiler[\"traverse-nodes\"]",      },
  ["val->node"] =           { tag = "var", contents = "_compiler[\"val->node\"]",           },
  ["var->symbol"] =         { tag = "var", contents = "_compiler[\"var->symbol\"]",         },
  ["visit-node"] =          { tag = "var", contents = "_compiler[\"visit-node\"]",          },
  ["visit-nodes"] =         { tag = "var", contents = "_compiler[\"visit-nodes\"]",         },
}
