return {
	['=']  = { tag = "expr", contents = "${1} == ${2}", count = 2, pure = true, prec = 3 },
	['/='] = { tag = "expr", contents = "${1} ~= ${2}", count = 2, pure = true, prec = 3 },
	['<']  = { tag = "expr", contents = "${1} < ${2}",  count = 2, pure = true, prec = 3 },
	['<='] = { tag = "expr", contents = "${1} <= ${2}", count = 2, pure = true, prec = 3 },
	['>']  = { tag = "expr", contents = "${1} > ${2}",  count = 2, pure = true, prec = 3 },
	['>='] = { tag = "expr", contents = "${1} >= ${2}", count = 2, pure = true, prec = 3 },

	['+']  = { tag = "expr", contents = "${1} + ${2}",  count = 2, pure = true, fold = "l", prec = 9  },
	['-']  = { tag = "expr", contents = "${1} - ${2}",  count = 2, pure = true, fold = "l", prec = 9  },
	['*']  = { tag = "expr", contents = "${1} * ${2}",  count = 2, pure = true, fold = "l", prec = 10 },
	['/']  = { tag = "expr", contents = "${1} / ${2}",  count = 2, pure = true, fold = "l", prec = 10 },
	['%']  = { tag = "expr", contents = "${1} % ${2}",  count = 2, pure = true, fold = "l", prec = 10 },
	['^']  = { tag = "expr", contents = "${1} ^ ${2}",  count = 2, pure = true, fold = "l", prec = 12 },
	['..'] = { tag = "expr", contents = "${1} .. ${2}", count = 2, pure = true, fold = "r", prec = 8  },

	['len#'] = { tag = "expr", contents = "#${1}",      count = 1, pure = true,             prec = 11 },

	['get-idx']  = { tag = "expr", contents = "${1}[${2}]",        count = 2, precs = { tag = "list", n = 2, 100, 0    } },
	['set-idx!'] = { tag = "stmt", contents = "${1}[${2}] = ${3}", count = 3, precs = { tag = "list", n = 3, 100, 0, 0 } },

	["_ENV"] =           { tag = "var", contents = "_ENV",           value = _ENV,                         },
	["_G"] =             { tag = "var", contents = "_G",             value = _G,                           },
	["assert"] =         { tag = "var", contents = "assert",         value = assert,                       },
	["arg#"] =           { tag = "var", contents = "arg",            value = arg,                          },
	["collectgarbage"] = { tag = "var", contents = "collectgarbage", value = collectgarbage,               },
	["dofile"] =         { tag = "var", contents = "dofile",         value = dofile,                       },
	["error"] =          { tag = "var", contents = "error",          value = error,                        },
	["getmetatable"] =   { tag = "var", contents = "getmetatable",   value = getmetatable,                 },
	["ipairs"] =         { tag = "var", contents = "ipairs",         value = ipairs,                       },
	["load"] =           { tag = "var", contents = "load",           value = load,                         },
	["loadfile"] =       { tag = "var", contents = "loadfile",       value = loadfile,                     },
	["next"] =           { tag = "var", contents = "next",           value = next,                         },
	["pairs"] =          { tag = "var", contents = "pairs",          value = pairs,                        },
	["pcall"] =          { tag = "var", contents = "pcall",          value = pcall,                        },
	["print"] =          { tag = "var", contents = "print",          value = print,                        },
	["rawequal"] =       { tag = "var", contents = "rawequal",       value = rawequal,       pure = true,  },
	["rawget"] =         { tag = "var", contents = "rawget",         value = rawget,                       },
	["rawlen"] =         { tag = "var", contents = "rawlen",         value = rawlen,                       },
	["rawset"] =         { tag = "var", contents = "rawset",         value = rawset,                       },
	["require"] =        { tag = "var", contents = "require",        value = require,                      },
	["select"] =         { tag = "var", contents = "select",         value = select,         pure = true,  },
	["setmetatable"] =   { tag = "var", contents = "setmetatable",   value = setmetatable,                 },
	["tonumber"] =       { tag = "var", contents = "tonumber",       value = tonumber,       pure = true,  },
	["tostring"] =       { tag = "var", contents = "tostring",       value = tostring,       pure = true,  },
	["type#"] =          { tag = "var", contents = "type",           value = type,           pure = true,  },
	["xpcall"] =         { tag = "var", contents = "xpcall",         value = xpcall,                       },
}
