return {
  ['=']  = { tag = "expr", contents = "${1} == ${2}", count = 2, pure = true, prec = 3 },
  ['/='] = { tag = "expr", contents = "${1} ~= ${2}", count = 2, pure = true, prec = 3 },
  ['<']  = { tag = "expr", contents = "${1} < ${2}",  count = 2, pure = true, prec = 3 },
  ['<='] = { tag = "expr", contents = "${1} <= ${2}", count = 2, pure = true, prec = 3 },
  ['>']  = { tag = "expr", contents = "${1} > ${2}",  count = 2, pure = true, prec = 3 },
  ['>='] = { tag = "expr", contents = "${1} >= ${2}", count = 2, pure = true, prec = 3 },

  ['+']  = { tag = "expr", contents = "${1} + ${2}",  count = 2, pure = true, fold = "l", prec = 9  },
  ['-']  = { tag = "expr", contents = "${1} - ${2}",  count = 2, pure = true, fold = "l", prec = 9  },
  ['*']  = { tag = "expr", contents = "${1} * ${2}",  count = 2, pure = true, fold = "l", prec = 10 },
  ['/']  = { tag = "expr", contents = "${1} / ${2}",  count = 2, pure = true, fold = "l", prec = 10 },
  ['..'] = { tag = "expr", contents = "${1} .. ${2}", count = 2, pure = true, fold = "r", prec = 8  },

  ['len#'] = { tag = "expr", contents = "#${1}",        count = 1, pure = true,             prec = 11 },
  ['mod']  = { tag = "expr", contents = "${1} % ${2}",  count = 2, pure = true, fold = "l", prec = 10 },
  ['expt'] = { tag = "expr", contents = "${1} ^ ${2}",  count = 2, pure = true, fold = "l", prec = 12 },

  ['get-idx']  = { tag = "expr", contents = "${1}[${2}]",        count = 2, precs = { tag = "list", n = 2, 100, 0    } },
  ['set-idx!'] = { tag = "stmt", contents = "${1}[${2}] = ${3}", count = 3, precs = { tag = "list", n = 3, 100, 0, 0 } },

  ["_ENV"] =           { tag = "var", contents = "_ENV",                         },
  ["_G"] =             { tag = "var", contents = "_G",                           },
  ["assert"] =         { tag = "var", contents = "assert",                       },
  ["arg#"] =           { tag = "var", contents = "arg or {...}",                 },
  ["collectgarbage"] = { tag = "var", contents = "collectgarbage",               },
  ["dofile"] =         { tag = "var", contents = "dofile",                       },
  ["error"] =          { tag = "var", contents = "error",                        },
  ["getmetatable"] =   { tag = "var", contents = "getmetatable",                 },
  ["ipairs"] =         { tag = "var", contents = "ipairs",                       },
  ["load"] =           { tag = "var", contents = "load",                         },
  ["loadfile"] =       { tag = "var", contents = "loadfile",                     },
  ["next"] =           { tag = "var", contents = "next",                         },
  ["pairs"] =          { tag = "var", contents = "pairs",                        },
  ["pcall"] =          { tag = "var", contents = "pcall",                        },
  ["print"] =          { tag = "var", contents = "print",                        },
  ["rawequal"] =       { tag = "var", contents = "rawequal",       pure = true,  },
  ["rawget"] =         { tag = "var", contents = "rawget",                       },
  ["rawlen"] =         { tag = "var", contents = "rawlen",                       },
  ["rawset"] =         { tag = "var", contents = "rawset",                       },
  ["require"] =        { tag = "var", contents = "require",                      },
  ["select"] =         { tag = "var", contents = "select",         pure = true,  },
  ["setmetatable"] =   { tag = "var", contents = "setmetatable",                 },
  ["tonumber"] =       { tag = "var", contents = "tonumber",       pure = true,  },
  ["tostring"] =       { tag = "var", contents = "tostring",       pure = true,  },
  ["type#"] =          { tag = "var", contents = "type",           pure = true,  },
  ["xpcall"] =         { tag = "var", contents = "xpcall",                       },
}
