return {
  ["debug"] =        { tag = "var", contents = "debug and debug.debug",        },
  ["gethook"] =      { tag = "var", contents = "debug and debug.gethook",      },
  ["getinfo"] =      { tag = "var", contents = "debug and debug.getinfo",      },
  ["getlocal"] =     { tag = "var", contents = "debug and debug.getlocal",     },
  ["getmetatable"] = { tag = "var", contents = "debug and debug.getmetatable", },
  ["getregistry"] =  { tag = "var", contents = "debug and debug.getregistry",  },
  ["getupvalue"] =   { tag = "var", contents = "debug and debug.getupvalue",   },
  ["getuservalue"] = { tag = "var", contents = "debug and debug.getuservalue", },
  ["sethook"] =      { tag = "var", contents = "debug and debug.sethook",      },
  ["setlocal"] =     { tag = "var", contents = "debug and debug.setlocal",     },
  ["setmetatable"] = { tag = "var", contents = "debug and debug.setmetatable", },
  ["setupvalue"] =   { tag = "var", contents = "debug and debug.setupvalue",   },
  ["setuservalue"] = { tag = "var", contents = "debug and debug.setuservalue", },
  ["traceback"] =    { tag = "var", contents = "debug and debug.traceback",    },
  ["upvalueid"] =    { tag = "var", contents = "debug and debug.upvalueid",    },
  ["upvaluejoin"] =  { tag = "var", contents = "debug and debug.upvaluejoin",  },
}
