return {
  ["close"] =   { tag = "var", contents = "io.close",   },
  ["flush"] =   { tag = "var", contents = "io.flush",   },
  ["input"] =   { tag = "var", contents = "io.input",   },
  ["lines"] =   { tag = "var", contents = "io.lines",   },
  ["open"] =    { tag = "var", contents = "io.open",    },
  ["output"] =  { tag = "var", contents = "io.output",  },
  ["popen"] =   { tag = "var", contents = "io.popen",   },
  ["read"] =    { tag = "var", contents = "io.read",    },
  ["stderr"] =  { tag = "var", contents = "io.stderr",  },
  ["stdin"] =   { tag = "var", contents = "io.stdin",   },
  ["stdout"] =  { tag = "var", contents = "io.stdout",  },
  ["tmpfile"] = { tag = "var", contents = "io.tmpfile", },
  ["type"] =    { tag = "var", contents = "io.type",    },
  ["write"] =   { tag = "var", contents = "io.write",   },
}
