return {
  ["abs"] =        { tag = "var", contents = "math.abs",        pure = true, },
  ["acos"] =       { tag = "var", contents = "math.acos",       pure = true, },
  ["asin"] =       { tag = "var", contents = "math.asin",       pure = true, },
  ["atan"] =       { tag = "var", contents = "math.atan",       pure = true, },
  ["atan2"] =      { tag = "var", contents = "math.atan2 or math.atan", pure = true, },
  ["ceil"] =       { tag = "var", contents = "math.ceil",       pure = true, },
  ["cos"] =        { tag = "var", contents = "math.cos",        pure = true, },
  ["deg"] =        { tag = "var", contents = "math.deg",        pure = true, },
  ["exp"] =        { tag = "var", contents = "math.exp",        pure = true, },
  ["floor"] =      { tag = "var", contents = "math.floor",      pure = true, },
  ["fmod"] =       { tag = "var", contents = "math.fmod",       pure = true, },
  ["huge"] =       { tag = "var", contents = "math.huge",       pure = true, },
  ["log"] =        { tag = "var", contents = "math.log",        pure = true, },
  ["max"] =        { tag = "var", contents = "math.max",        pure = true, },
  ["maxinteger"] = { tag = "var", contents = "math.maxinteger", pure = true, },
  ["min"] =        { tag = "var", contents = "math.min",        pure = true, },
  ["mininteger"] = { tag = "var", contents = "math.mininteger", pure = true, },
  ["modf"] =       { tag = "var", contents = "math.modf",       pure = true, },
  ["pi"] =         { tag = "var", contents = "math.pi",         pure = true, },
  ["rad"] =        { tag = "var", contents = "math.rad",        pure = true, },
  ["random"] =     { tag = "var", contents = "math.random",                  },
  ["randomseed"] = { tag = "var", contents = "math.randomseed",              },
  ["sin"] =        { tag = "var", contents = "math.sin",        pure = true, },
  ["sqrt"] =       { tag = "var", contents = "math.sqrt",       pure = true, },
  ["tan"] =        { tag = "var", contents = "math.tan",        pure = true, },
  ["tointeger"] =  { tag = "var", contents = "math.tointeger",  pure = true, },
  ["type"] =       { tag = "var", contents = "math.type",       pure = true, },
  ["ult"] =        { tag = "var", contents = "math.ult",        pure = true, },
}
