(define-native abs        :bind-to "math.abs"        :pure)
(define-native acos       :bind-to "math.acos"       :pure)
(define-native asin       :bind-to "math.asin"       :pure)
(define-native atan       :bind-to "math.atan"       :pure)
(define-native atan2      :bind-to "math.atan2 or math.atan" :pure)
(define-native ceil       :bind-to "math.ceil"       :pure)
(define-native cos        :bind-to "math.cos"        :pure)
(define-native deg        :bind-to "math.deg"        :pure)
(define-native exp        :bind-to "math.exp"        :pure)
(define-native floor      :bind-to "math.floor"      :pure)
(define-native fmod       :bind-to "math.fmod"       :pure)
(define-native huge       :bind-to "math.huge"       :pure)
(define-native log        :bind-to "math.log"        :pure)
(define-native max        :bind-to "math.max"        :pure)
(define-native maxinteger :bind-to "math.maxinteger" :pure)
(define-native min        :bind-to "math.min"        :pure)
(define-native mininteger :bind-to "math.mininteger" :pure)
(define-native modf       :bind-to "math.modf"       :pure)
(define-native pi         :bind-to "math.pi"         :pure)
(define-native rad        :bind-to "math.rad"        :pure)
(define-native random     :bind-to "math.random")
(define-native randomseed :bind-to "math.randomseed")
(define-native sin        :bind-to "math.sin"        :pure)
(define-native sqrt       :bind-to "math.sqrt"       :pure)
(define-native tan        :bind-to "math.tan"        :pure)
(define-native tointeger  :bind-to "math.tointeger"  :pure)
(define-native type       :bind-to "math.type"       :pure)
(define-native ult        :bind-to "math.ult"        :pure)
