(define-native config     :bind-to "package.config")
(define-native cpath      :bind-to "package.cpath")
(define-native loaded     :bind-to "package.loaded")
(define-native loadlib    :bind-to "package.loadlib")
(define-native path       :bind-to "package.path")
(define-native preload    :bind-to "package.preload")
(define-native searchers  :bind-to "package.searchers")
(define-native searchpath :bind-to "package.searchpath")
