(define-native concat :bind-to "table.concat")
(define-native insert :bind-to "table.insert")
(define-native move   :bind-to "table.move")
(define-native pack   :bind-to "table.pack")
(define-native remove :bind-to "table.remove")
(define-native sort   :bind-to "table.sort")
(define-native unpack :bind-to "table.unpack")
