(define-native  char        :bind-to  "utf8.char"        :pure)
(define-native  charpattern :bind-to  "utf8.charpattern" :pure)
(define-native  codepoint   :bind-to  "utf8.codepoint"   :pure)
(define-native  codes       :bind-to  "utf8.codes"       :pure)
(define-native  len         :bind-to  "utf8.len"         :pure)
(define-native  offset      :bind-to  "utf8.offset"      :pure)
