return {
  ["C"] =        { tag = "var", contents = "require('ffi').C",        },
  ["abi"] =      { tag = "var", contents = "require('ffi').abi",      },
  ["alignof"] =  { tag = "var", contents = "require('ffi').alignof",  },
  ["arch"] =     { tag = "var", contents = "require('ffi').arch",     },
  ["cast"] =     { tag = "var", contents = "require('ffi').cast",     },
  ["cdef"] =     { tag = "var", contents = "require('ffi').cdef",     },
  ["copy"] =     { tag = "var", contents = "require('ffi').copy",     },
  ["errno"] =    { tag = "var", contents = "require('ffi').errno",    },
  ["fill"] =     { tag = "var", contents = "require('ffi').fill",     },
  ["gc"] =       { tag = "var", contents = "require('ffi').gc",       },
  ["istype"] =   { tag = "var", contents = "require('ffi').istype",   },
  ["load"] =     { tag = "var", contents = "require('ffi').load",     },
  ["metatype"] = { tag = "var", contents = "require('ffi').metatype", },
  ["new"] =      { tag = "var", contents = "require('ffi').new",      },
  ["offsetof"] = { tag = "var", contents = "require('ffi').offsetof", },
  ["os"] =       { tag = "var", contents = "require('ffi').os",       },
  ["sizeof"] =   { tag = "var", contents = "require('ffi').sizeof",   },
  ["string"] =   { tag = "var", contents = "require('ffi').string",   },
  ["typeinfo"] = { tag = "var", contents = "require('ffi').typeinfo", },
  ["typeof"] =   { tag = "var", contents = "require('ffi').typeof",   },
}
