(define-native on          :bind-to "require('jit').on")
(define-native off         :bind-to "require('jit').off")
(define-native flush       :bind-to "require('jit').flush)")
(define-native status      :bind-to "require('jit').status)")
(define-native version     :bind-to "require('jit').version)")
(define-native version-num :bind-to "require('jit').version_num)")
(define-native os          :bind-to "require('jit').os)")
(define-native arch        :bind-to "require('jit').arch)")
